### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by pranjalrajp** [1Danish-00/CompressorBot#2]
I am not able to deploy it on heroku....

Logs

NameError: name 'LOGS' is not defined
2021-04-14T02:22:22.679480+00:00 heroku[worker.1]: Starting process with command `/bin/sh -c bash\ run.sh`
2021-04-14T02:22:23.377458+00:00 heroku[worker.1]: State changed from starting to up
2021-04-14T02:22:27.466718+00:00 heroku[worker.1]: Process exited with status 1
2021-04-14T02:22:27.569118+00:00 heroku[worker.1]: State changed from up to crashed
2021-04-14T02:22:27.281915+00:00 app[worker.1]: Traceback (most recent call last):
2021-04-14T02:22:27.281951+00:00 app[worker.1]:   File "/bot/helper/config.py", line 21, in <module>
2021-04-14T02:22:27.282130+00:00 app[worker.1]:     OWNER = config("OWNER_ID", default=1322549723, cast=int)
2021-04-14T02:22:27.282135+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/decouple.py", line 199, in __call__
2021-04-14T02:22:27.282452+00:00 app[worker.1]:     return self.config(*args, **kwargs)
2021-04-14T02:22:27.282457+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/decouple.py", line 83, in __call__
2021-04-14T02:22:27.282656+00:00 app[worker.1]:     return self.get(*args, **kwargs)
2021-04-14T02:22:27.282660+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/decouple.py", line 77, in get
2021-04-14T02:22:27.282844+00:00 app[worker.1]:     return cast(value)
2021-04-14T02:22:27.282889+00:00 app[worker.1]: ValueError: invalid literal for int() with base 10: ''
2021-04-14T02:22:27.282890+00:00 app[worker.1]: 
2021-04-14T02:22:27.282891+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2021-04-14T02:22:27.282891+00:00 app[worker.1]: 
2021-04-14T02:22:27.282895+00:00 app[worker.1]: Traceback (most recent call last):
2021-04-14T02:22:27.282897+00:00 app[worker.1]:   File "/bot/start.py", line 16, in <module>
2021-04-14T02:22:27.283064+00:00 app[worker.1]:     from helper._get import *
2021-04-14T02:22:27.283068+00:00 app[worker.1]:   File "/bot/helper/_get.py", line 1, in <module>
2021-04-14T02:22:27.283257+00:00 app[worker.1]:     from .devtools import *
2021-04-14T02:22:27.283258+00:00 app[worker.1]:   File "/bot/helper/devtools.py", line 15, in <module>
2021-04-14T02:22:27.283401+00:00 app[worker.1]:     from .stuff import *
2021-04-14T02:22:27.283406+00:00 app[worker.1]:   File "/bot/helper/stuff.py", line 15, in <module>
2021-04-14T02:22:27.283582+00:00 app[worker.1]:     from .worker import *
2021-04-14T02:22:27.283586+00:00 app[worker.1]:   File "/bot/helper/worker.py", line 15, in <module>
2021-04-14T02:22:27.283762+00:00 app[worker.1]:     from .funcn import *
2021-04-14T02:22:27.283766+00:00 app[worker.1]:   File "/bot/helper/funcn.py", line 15, in <module>
2021-04-14T02:22:27.283957+00:00 app[worker.1]:     from .config import *
2021-04-14T02:22:27.283957+00:00 app[worker.1]:   File "/bot/helper/config.py", line 24, in <module>
2021-04-14T02:22:27.284116+00:00 app[worker.1]:     LOGS.info("Environment vars Missing")
2021-04-14T02:22:27.284120+00:00 app[worker.1]: NameError: name 'LOGS' is not defined

**Comment by buddhhu** [comment]
Try now @pranjalrajp

**Comment by 1Danish-00** [comment]
Add Bot to a channel/group make it admin and save that channel/group id in LOG_CHANNEL config
